name: X016.BIN
sha1: 7c93915bc943e8d9d8fa5d5efbd02f7e563650e4
options:
  basename: x016
  target_path: game/AREA16/X016.BIN
  base_path: ..
  platform: psx
  compiler: PSYQ
  asm_path: asm/x016
  src_path: build/splat_src/x016
  build_path: build
  ld_script_path: build/x016.ld
  symbol_addrs_path:
    - config/symbol_addrs_x016.txt
    - config/symbol_addrs_main0.txt
  undefined_funcs_auto_path: build/undefined_funcs_auto.x016.txt
  undefined_syms_auto_path: build/undefined_syms_auto.x016.txt
  find_file_boundaries: False
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".bss"]
  subalign: 4
  string_encoding: ASCII
segments:
  - name: x016
    type: code
    start: 0x0
    vram: 0x800E8028
    align: 4
    subalign: 4
    subsegments:
      - [0x0, c, x016]
  - [0x33704]
