name: X017.BIN
sha1: 59c5964cbb4536bc62b1a65262d963fab1ad3d33
options:
  basename: x017
  target_path: game/AREA17/X017.BIN
  base_path: ..
  platform: psx
  compiler: PSYQ
  asm_path: asm/x017
  src_path: build/splat_src/x017
  build_path: build
  ld_script_path: build/x017.ld
  symbol_addrs_path:
    - config/symbol_addrs_x017.txt
    - config/symbol_addrs_main0.txt
  undefined_funcs_auto_path: build/undefined_funcs_auto.x017.txt
  undefined_syms_auto_path: build/undefined_syms_auto.x017.txt
  find_file_boundaries: False
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".bss"]
  subalign: 4
  string_encoding: ASCII
segments:
  - name: x017
    type: code
    start: 0x0
    vram: 0x800E8028
    align: 4
    subalign: 4
    subsegments:
      - [0x0, c, x017]
  - [0x34678]
