name: X018.BIN
sha1: 83eca42eb30944bb0c61056632b2ef7bb9891b34
options:
  basename: x018
  target_path: game/AREA18/X018.BIN
  base_path: ..
  platform: psx
  compiler: PSYQ
  asm_path: asm/x018
  src_path: build/splat_src/x018
  build_path: build
  ld_script_path: build/x018.ld
  symbol_addrs_path:
    - config/symbol_addrs_x018.txt
    - config/symbol_addrs_main0.txt
  undefined_funcs_auto_path: build/undefined_funcs_auto.x018.txt
  undefined_syms_auto_path: build/undefined_syms_auto.x018.txt
  find_file_boundaries: False
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".bss"]
  subalign: 4
  string_encoding: ASCII
segments:
  - name: x018
    type: code
    start: 0x0
    vram: 0x800E8028
    align: 4
    subalign: 4
    subsegments:
      - [0x0, c, x018]
  - [0x34D2C]
